### ISSUE TITLE
Node memory leak during compare process

### ISSUE THREAD

**Issue by ggiacomo** [garris/BackstopJS#281]
Hi all,
I've almost 1000 page to check with backstopjs. During the test process my computer freezes.
I've tried again looking at process list, top command, and saw node process increasing cpu/memory usage, like 100/110% cpu and 60/70 memory.

Any Idea?

**Comment by garris** [comment]
Are you using version 1.x or 2beta?

**Comment by garris** [comment]
If you're using 1.x -- please try upgrading to the 2 Beta.   (please not subtle install and config changes in the version 2 documentation).  Please let me know how that goes for you.

**Comment by ggiacomo** [comment]
Hi @garris,
I've already switched to 2beta, as  I had the same issue wth 1.x.
Note: in util/compare.js is used a deprecated function [fs.existsSync](https://nodejs.org/api/fs.html#fs_fs_existssync_path)

thank you!

**Comment by garris** [comment]
Ok then.  I don't think its a memory leak so much as a straight ahead stack overflow.   I am pretty sure that all scenarios are processed in parallel inside of casper -- so it's not a big surprise things are bottoming out. 

Ideally we could implement some kind of async `limit` like this... http://caolan.github.io/async/docs.html#.everyLimit

But as an incremental step we could try to integrate a casper.eachThen() here.  I think this would serialize the processes... https://github.com/garris/BackstopJS/blob/version_2_0/capture/genBitmaps.js#L63

And as a quick fix you could break your tests up into separate files and run them serially on your command line.   Pull down the latest version 2 and you can use the same data paths for your resources.  I am still working on the documentation so feel free to ping with questions -- I'll answer as many as I can after hours.

Please let me know how this works out.

**Comment by ggiacomo** [comment]
Thank you for your suggestion. With more than 100 url for each test, the result is still the same, freezing the machine.
I had to split every 50 url in order to do the test completely.
At this point, is there a way to have different html/config file names for each test in browser format? like html_1.html/config_1.js and so on? Right now I'm using the cnofig path with a dynamic suffix for the html folder, like
     
"html_report": "backstop_data/html_report_"+INCREMENT_TEST_COUNT

but with this solution I've a lot of duplicated folders/files(for bower_components,css,js)

Thank you!

offtopic: My final purpose is to run tests with a cron job every x days, and send the test response via email. Any suggestion to accomplish this task?

**Comment by ggiacomo** [comment]
As a temporary, I'm using the ci_report, in this way a can set the name for the xml report file. Than using a junit viewer to preview all test results.

**Comment by garris** [comment]
Can you restate your question about file names? I am not sure what your question is.   You can change the file naming format -- see the readme under "Migrating to 2.0"

**Comment by Patabugen** [comment]
I'm also running out of memory (I have 4GB and nothing else running) with 29 URLs and 5 screen sizes.

I can grab everything just fine - after comparing my process gets killed for using up all the memory.

I'm increasing the memory to 6GB - but it would be great if there was some way to clear out the used memory between comparisons to effectively remove the limit on number of URLs.

**Comment by Primajin** [comment]
I also ran into that, and also my Travis CI. Would be great if we could find a nice tweak that balances speed and memory usage.

**Comment by Primajin** [comment]
I also ran into that, and also my Travis CI. Would be great if we could find a nice tweak that balances speed and memory usage.

**Comment by mirzazeyrek** [comment]
Actually I have made an improvement for limiting simultaneous comparisons with 10 images but it was pretty ugly workaround may be I try to implement more advanced version in 2.0 and submit a PR. What do you think @garris  ? Would it be helpful ?

**Comment by garris** [comment]
@mirzazeyrek limiting simultaneous comparisons was already implemented in master -- unfortunately this by itself is not enough.  The resemble object also needs to be cleaned up after each individual comparison is completed -- one more step is needed.   Please check this issue for details https://github.com/garris/BackstopJS/issues/329 -- and by all means, please do contribute a PR if you are so inspired!  😺

**Comment by garris** [comment]
Fixed by https://github.com/garris/BackstopJS/releases/tag/v2.3.4

**Comment by sebastianekstrom** [comment]
I'm still experiencing this issue while running it on a Heroku app.

Node: `7.5.0`
Backstop.JS: `~2.6.11`

The compare process goes through 17 different screens in two different viewports and ends up using ~2.5GB of memory. I've tried to lower the `asyncCompareLimit` but that doesn't make any difference. The config can be found [here](https://gist.github.com/sebastianekstrom/6280758a7558e4626c3f16eb298c1bda).

Any ideas?
