### ISSUE TITLE
Chromy - Error: Failed to launch a browser. 11 SIGINT listeners added

### ISSUE THREAD

**Issue by digitalpencil** [garris/BackstopJS#514]
When attempting to run backstop reference/test against 13 scenarios across 3 viewports, backstop reliably outputs a node EventEmitter memory leak detected error, followed by "Error: Failed to launch a browser" and then continues through the scenarios but fails to complete the test or open the report.

Running each scenario separately through --filter completes each test successfully. Adjusting asyncCaptureLimit and asyncCompareLimit seemingly has no effect on the error.

macOS 10.12.6
Chrome Version 60.0.3112.113
node -v v6.11.2
npm -v 3.10.10
backstop -v BackstopJS v3.0.14
BackstopJS 3.0.14 

```
Starting Chromy: port:9232 --window-size=768,1024
(node:44100) Warning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
Starting Chromy: port:9233 --window-size=1268,1024
Starting Chromy: port:9234 --window-size=320,1024
Error: Failed to launch a browser.
    at Chromy.start$ (/usr/local/lib/node_modules/backstopjs/node_modules/chromy/dist/index.js:148:21)
    at tryCatch (/usr/local/lib/node_modules/backstopjs/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/backstopjs/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:299:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/backstopjs/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:117:21)
    at tryCatch (/usr/local/lib/node_modules/backstopjs/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:65:40)
    at invoke (/usr/local/lib/node_modules/backstopjs/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:155:20)
    at /usr/local/lib/node_modules/backstopjs/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:165:13
```

backstop.json

```
{
  "id": "pm",
  "viewports": [
    {
      "label": "phone",
      "width": 320,
      "height": 1024
    },
    {
      "label": "tablet",
      "width": 768,
      "height": 1024
    },
    {
      "label": "desktop",
      "width": 1268,
      "height": 1024
    }
  ],
  "scenarios": [
    {
      "label": "header",
      "url": "http://scratch.local/bb-prototype-website_example_grid.html",
      "selectors": [
        "#header"
      ],
      "hideSelectors": [
        "#monitor_mq",
        ".grid",
        ".visible-grid-btn"
      ],
      "readySelector": ".page-loaded"
    },
    {
      "label": "burgerMenu",
      "url": "http://scratch.local/bb-prototype-website_example_grid.html",
      "selectors": [
        "#header",
        "#smallscreen-navigation"
      ],
      "hideSelectors": [
        "#monitor_mq",
        ".grid",
        ".visible-grid-btn"
      ],
      "readySelector": ".page-loaded",
      "onReadyScript": "burgerMenuTest.js",
      "someOnReadyScriptParameter": "html.page-loaded"
    },
    {
      "label": "footer",
      "url": "http://scratch.local/bb-prototype-website_example_grid.html",
      "selectors": [
        "#site-footer"
      ],
      "hideSelectors": [
        "#monitor_mq",
        ".grid",
        ".visible-grid-btn"
      ],
      "readySelector": ".page-loaded"
    },
    {
      "label": "articleHeader",
      "url": "http://scratch.local/bb-prototype-website_components-article-header.html",
      "selectors": [
        ".article-header"
      ],
      "hideSelectors": [
        "#monitor_mq"
      ],
      "readySelector": ".page-loaded"
    },
    {
      "label": "ctaPrompt",
      "url": "http://scratch.local/bb-prototype-website_components-cta-prompt.html",
      "selectors": [
        ".cta-prompt"
      ],
      "hideSelectors": [
        "#monitor_mq"
      ],
      "readySelector": ".page-loaded"
    },
    {
      "label": "editorsPicks",
      "url": "http://scratch.local/bb-prototype-website_components-editors-picks.html",
      "selectors": [
        ".editors-picks"
      ],
      "hideSelectors": [
        "#monitor_mq"
      ],
      "readySelector": ".page-loaded"
    },
    {
      "label": "freeTextBlock",
      "url": "http://scratch.local/bb-prototype-website_components-free-text-block.html",
      "selectors": [
        ".free-text-block"
      ],
      "hideSelectors": [
        "#monitor_mq"
      ],
      "readySelector": ".page-loaded"
    },
    {
      "label": "listingComponent",
      "url": "http://scratch.local/bb-prototype-website_components-listing-component.html",
      "selectors": [
        ".article-list"
      ],
      "hideSelectors": [
        "#monitor_mq"
      ],
      "readySelector": ".page-loaded"
    },
    {
      "label": "primaryFeature",
      "url": "http://scratch.local/bb-prototype-website_components-primary-feature.html",
      "selectors": [
        ".primary-feature"
      ],
      "hideSelectors": [
        "#monitor_mq"
      ],
      "readySelector": ".page-loaded"
    },
    {
      "label": "trendingList",
      "url": "http://scratch.local/bb-prototype-website_components-trending-list.html",
      "selectors": [
        ".article-list"
      ],
      "hideSelectors": [
        "#monitor_mq"
      ],
      "readySelector": ".page-loaded"
    },
    {
      "label": "videoContainer",
      "url": "http://scratch.local/bb-prototype-website_components-video-container.html",
      "selectors": [
        ".video-container"
      ],
      "hideSelectors": [
        "#monitor_mq"
      ],
      "readySelector": ".page-loaded"
    },
    {
      "label": "searchResults",
      "url": "http://scratch.local/bb-prototype-website_search-results.html",
      "selectors": [
        ".search-results"
      ],
      "hideSelectors": [
        "#monitor_mq"
      ],
      "readySelector": ".page-loaded"
    },
    {
      "label": "relatedContent",
      "url": "http://scratch.local/bb-prototype-website_components-related-content.html",
      "selectors": [
        ".article-list"
      ],
      "hideSelectors": [
        "#monitor_mq"
      ],
      "readySelector": ".page-loaded"
    }
  ],
  "paths": {
    "bitmaps_reference": "backstop_data/bitmaps_reference",
    "bitmaps_test": "backstop_data/bitmaps_test",
    "engine_scripts": "backstop_data/engine_scripts",
    "html_report": "backstop_data/html_report",
    "ci_report": "backstop_data/ci_report"
  },
  "asyncCaptureLimit": 10,
  "asyncCompareLimit": 200,
  "engineFlags": [],
  "engine": "chrome",
  "report": ["browser"],
  "debug": false,
  "debugWindow": false
}
```

**Comment by garris** [comment]
Please upgrade to chrome-canary and backstop 3.0.19 -- I think this should fix the issue...

https://www.google.com/chrome/browser/canary.html

`npm install -g backstopjs`

**Comment by digitalpencil** [comment]
Thanks @garris , problem persists though and has gotten worse.

Installed Chrome Canary Version 62.0.3199.0 (Official Build) canary (64-bit)
backstop -v BackstopJS v3.0.22 BackstopJS 3.0.22

Reference/test fails on fifth scenario, regardless of what scenario that is (i can shuffle the order around and will always fail on fifth). Each reference/test will again complete, if run individually, through filter.

```
backstop test
BackstopJS v3.0.22
Loading config:  /Users/davegrant/Sites/scratch/html/backstop.json

COMMAND | Executing core for `test`
createBitmaps | Selcted 13 of 13 scenarios.
Starting Chromy: port:9222 --disable-gpu,--force-device-scale-factor=1,--window-size=320,1024
Starting Chromy: port:9223 --disable-gpu,--force-device-scale-factor=1,--window-size=768,1024
Starting Chromy: port:9224 --disable-gpu,--force-device-scale-factor=1,--window-size=1268,1024
Starting Chromy: port:9225 --disable-gpu,--force-device-scale-factor=1,--window-size=320,1024
>>>
[Function]
Starting Chromy: port:9226 --disable-gpu,--force-device-scale-factor=1,--window-size=768,1024
>>>
[Function]
Starting Chromy: port:9227 --disable-gpu,--force-device-scale-factor=1,--window-size=1268,1024
>>>
[Function]
Starting Chromy: port:9228 --disable-gpu,--force-device-scale-factor=1,--window-size=320,1024
Starting Chromy: port:9229 --disable-gpu,--force-device-scale-factor=1,--window-size=768,1024
Starting Chromy: port:9230 --disable-gpu,--force-device-scale-factor=1,--window-size=1268,1024
Starting Chromy: port:9231 --disable-gpu,--force-device-scale-factor=1,--window-size=320,1024
9227 LOG >  Testing viewport: desktop
9225 LOG >  Testing viewport: phone
Starting Chromy: port:9232 --disable-gpu,--force-device-scale-factor=1,--window-size=768,1024
Starting Chromy: port:9233 --disable-gpu,--force-device-scale-factor=1,--window-size=1268,1024
Starting Chromy: port:9234 --disable-gpu,--force-device-scale-factor=1,--window-size=320,1024
      COMMAND | Command `test` ended with an error after [12.003s]
      COMMAND | BackstopExcpetion: ctaPrompt on undefined: Error: Failed to launch a browser.
9226 LOG >  Testing viewport: tablet
```

Increasing asyncCompareLimit from 200 to 400 additionally outputs the aforementioned 11 SIGINIT listeners added error.

**Comment by garris** [comment]
Have you tried upgrading to node 8.1?

**Comment by garris** [comment]
Also,  set asyncCaptureLimit & asyncCompareLimit both to 1.

**Comment by digitalpencil** [comment]
@garris i think it might have been a timeout error.. i'm not too sure. it seems to be more reliable now.

I've been monitoring memory usage but machine has 16GB so shouldn't be overrunning and barely scrapes 4GB used while tests are running.

I've just run a test with "asyncCaptureLimit": 20,  "asyncCompareLimit": 400 and despite output of SIGINT error, all tests completed successfully.

Running with 1 for both completes as well, albeit much slower.

Closing as I believe this has resolved it however i'll keep an eye on it and let you know of any changes.

Thanks

**Comment by garris** [comment]
Thanks for the feedback -- cheers!

**Comment by laubsauger** [comment]
Just want to chime in here:
I get the same SIGINT Listeners error output as soon as i have more than five scenarios defined.

BackstopJS 3.0.19
Chrome 61.0.3163.79 64-bit
Node 8.4.0
CentOS7

No scripts are used.

no SIGINT Error:
````json
"scenarios": [
    {
      "label": "1",
      "url": "https://www.google.com",
      "referenceUrl": "https://www.google.com"
    },
    {
      "label": "2",
      "url": "https://www.google.com",
      "referenceUrl": "https://www.google.com"
    },
    {
      "label": "3",
      "url": "https://www.google.com",
      "referenceUrl": "https://www.google.com"
    },
    {
      "label": "4",
      "url": "https://www.google.com",
      "referenceUrl": "https://www.google.com"
    },
    {
      "label": "5",
      "url": "https://www.google.com",
      "referenceUrl": "https://www.google.com"
    }
  ]
````

SIGINT Error:
````json
  "scenarios": [
    {
      "label": "1",
      "url": "https://www.google.com",
      "referenceUrl": "https://www.google.com"
    },
    {
      "label": "2",
      "url": "https://www.google.com",
      "referenceUrl": "https://www.google.com"
    },
    {
      "label": "3",
      "url": "https://www.google.com",
      "referenceUrl": "https://www.google.com"
    },
    {
      "label": "4",
      "url": "https://www.google.com",
      "referenceUrl": "https://www.google.com"
    },
    {
      "label": "5",
      "url": "https://www.google.com",
      "referenceUrl": "https://www.google.com"
    },
    {
      "label": "6",
      "url": "https://www.google.comn",
      "referenceUrl": "https://www.google.com"
    }
  ]
````

**Comment by stephenbe** [comment]
Hey @garris  we are having the same error. We are tried installing chrome canary but backstop doesn't seem to find chrome. 

Now we didn't upgrade our backstop yet, but wondering if their is anything we can do for canary

Thanks!
